version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errorlint
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 60
    goconst:
      min-len: 6
      min-occurrences: 3
      ignore-calls: true
      numbers: false
      ignore-tests: true
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    mnd:
      checks:
        - operation
        - return
        - assign
      ignored-numbers:
        - "2"
        - "24"
        - "24.0"
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      confidence: 1
  exclusions:
    generated: lax
    presets:
      - std-error-handling
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fmotalleb/edged
